version: '3.8'

services:
  db:
    image: postgres:15
    container_name: meu_postgres
    restart: always
    environment:
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha_forte
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meu_usuario -d meu_banco"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    container_name: api_publicacoes
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: meu_usuario
      DB_PASSWORD: minha_senha_forte
      DB_DATABASE: meu_banco
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "start"]

volumes:
  pgdata:
